### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wiredmatt** [routayush1/animexninja-api#2]
Hello, I don't see a license file, I would like to fork this and add some features as well as replacing request with axios, making stuff asynchronous, etc. In case this project is not open source just tell me, but [a repo without license is understood as a not open source project.](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)

**Comment by routayush1** [comment]
hey , this project was made just for fun ,and i don't really have a thought of licensing it, i made it just for educational purpose
