### ISSUE TITLE
PLEASE FIX THIS :D

### ISSUE THREAD

**Issue by Ashweru** [routayush1/animexninja-api#3]
![Screenshot_20210304_232853](https://user-images.githubusercontent.com/77178801/109987268-712c3180-7d41-11eb-9375-dfd7f15e26f3.jpg)
I really want to watch anime rn but i cant cuz of this please fix

**Comment by Ashweru** [comment]
![Screenshot_20210304_233009](https://user-images.githubusercontent.com/77178801/109987455-9a4cc200-7d41-11eb-9f1a-9003920f8880.jpg)
Unli Loading too

**Comment by saishankar404** [comment]
Its your Internet Fault
Use better internet
xD
